# Default initial positions for ur5_leap_classic's ros2_control fake system

initial_positions:
  arm_elbow_joint: 0
  arm_shoulder_lift_joint: 0
  arm_shoulder_pan_joint: 0
  arm_wrist_1_joint: 0
  arm_wrist_2_joint: 0
  arm_wrist_3_joint: 0