controller_joint_names: ['', 'thumb_joint1', 'thumb_joint2', 'thumb_joint3', 'index_joint1', 'index_joint2', 'middle_joint1', 'middle_joint2', 'ring_joint1', 'ring_joint2', 'little_joint1', 'little_joint2', ]
